services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: barbershop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/trim-booking-api/scripts/docker-init.sql:/docker-entrypoint-initdb.d/01-init.sql

  api:
    build: ./backend/trim-booking-api
    container_name: trim_booking_api
    restart: always
    env_file:
      - ./backend/trim-booking-api/.env
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/barbershop_db
      SPRING_PROFILES_ACTIVE: rls
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: trim_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
