### Register Customer
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Ariel",
  "lastName": "Nunes",
  "email": "arielcassiano321@gmail.com",
  "password": "password123",
  "phone": "0871234567"
}

### Login as customer
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "arielcassiano321@gmail.com",
  "password": "password123"
}

### Login as Barber
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "mike@barbershop.com",
  "password": "password123"
}

### Login as Admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@barbershop.com",
  "password": "admin123"
}

### Get All Services (Protected - needs token)
GET http://localhost:8080/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJ1c2VySWQiOjEsInN1YiI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjAzNDM1NjEsImV4cCI6MTc2MDQyOTk2MX0.GUwcT6yGuQ1A4Mumd2Rf01mzxycVpEQUb-Yu_dD82Qc

### Get All Services (No token - should fail)
GET http://localhost:8080/api/services

### Register Admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "admin@barbershop.com",
  "password": "admin123",
  "phone": "0871234569"
}

### Login as Admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@barbershop.com",
  "password": "admin123"
}